### ISSUE TITLE
Tracking Issue: Replace big `cfg!` chunks with shorter aliases

### ISSUE THREAD

**Issue by SteveLauC** [nix-rust/nix#2188]
## Background

With the crate [`cfg_aliases`](https://crates.io/crates/cfg_aliases), we can replace common, chunky `cfg!`s with shorter aliases, here are the aliases defined by us:

* apple_targets: `any(ios, macos, watchos, tvos)`
* freebsdlike: `any(freebsd, dragonfly)`
* bsd: `any(freebsd, dragonfly, netbsd, openbsd, apple_targets)`
* linux_android: `any(linux, android)`
* solarish: `any(illumos, solaris)`

#2205 has done most of the replacements, but there are still `cfg!`s that haven't been updated, we want to clear them all.

## TODO

Scan our source code, and replace the long `cfg!` chunks with shorter aliases:

* [x] `src/dir.rs` `src/env.rs` (#2214)
* [x] `src/errno.rs` (#2214)
* [ ] `src/fcntl.rs` (#2215)
* [ ] `src/features.rs` `src/ifaddrs.rs` (#2215)
* [ ] `src/kmod.rs` `src/lib.rs` (#2215)
* [ ] `src/macro.rs` (#2215)
* [ ] `src/mqueue.rs` (#2215)
* [ ] `src/poll.rs` (#2215)
* [ ] `src/pty.rs` (#2215)
* [ ] `src/sched.rs` (#2215)
* [ ] `src/time.rs` (#2215)
* [x] `src/unistd.rs` (#2216)
* [x] `src/mount/bsd.rs` (#2217)
* [x] `src/mount/linux.rs` `src/mount/mod.rs` (#2217)
* [x] `src/net/if_.rs` (#2217)
* [x] `src/sys/aio.rs` (#2218)
* [x] `src/sys/epoll.rs` (#2218)
* [x] `src/sys/event.rs` (#2218)
* [x] `src/sys/mman.rs` (#2218)
* [x] `src/sys/mod.rs` (#2218)
* [x] `src/sys/resource.rs` (#2218)
* [x] `src/sys/sendfile.rs` (#2218)
* [x] `src/sys/signal.rs` (#2218)
* [x] `src/sys/stat.rs` (#2219)
* [x] `src/sys/statfs.rs` (#2219)
* [x] `src/sys/termios.rs` (#2220)
* [ ] `src/sys/time.rs` (#2229)
* [x] `src/sys/uio.rs` `src/sys/wait.rs` (#2221)
* [x] `src/sys/ioctl/mod.rs` (#2222)
* [x] `src/sys/ptrace/mod.rs` `src/sys/ptrace/bsd.rs` (#2222)
* [x] `src/sys/socket/addr.rs` (#2223)
* [x] `src/sys/socket/mod.rs` (#2224)
* [x] `src/sys/socket/sockopt.rs` (#2225)
* [ ] `test/common/mod.rs` (#2230)
* [ ] `test/sys/mod.rs` `test/sys/test_socket.rs` (#2230)
* [ ] `test/sys/test_sockopt.rs` (#2230)
* [ ] `test/test.rs` (#2230)
* [ ] `test/test_fcntl.rs` (#2230)
* [ ] `test/test_net.rs` `test/test_poll.rs` (#2230)
* [ ] `test/test_sendfile.rs` (#2230)
* [ ] `test/test_stat.rs` (#2230)
* [ ] `test/test_time.rs` (#2230)
* [ ] `test/test_unistd.rs` (#2230)
