### ISSUE TITLE
Tracking issue for keeping a change log (RFC 3)

### ISSUE THREAD

**Issue by kamalmarhubi** [nix-rust/nix#390]
https://github.com/nix-rust/rfcs/blob/master/text/0003-use-changelog.md
https://github.com/nix-rust/rfcs/pull/3

Items from RFC:
- [ ] add initial CHANGELOG.md, going back to 0.5.0 per https://github.com/nix-rust/nix/issues/363#issuecomment-232621388
- [x] add section to CONRTIBUTING.md
- [x] add section to new RELEASE_PROCEDURE.md file

**Comment by Susurrus** [comment]
I'm going to propose that we leave this at the current 0.5.0 cutoff as this is already almost a year-old issue that hasn't been resolved. As RFC3 doesn't indicate how far back the CHANGELOG should go, just that one is actively maintained, this is also in line with that RFC.
