### ISSUE TITLE
Release 0.9.0

### ISSUE THREAD

**Issue by asomers** [nix-rust/nix#632]
I think it's time to make a new release.  It should definitely include a fix for issue #610, and possibly any other PRs that are close to completion.  But it should not include PR #630 , because that depends on an unreleased version of libc.

 * [x] #527 - Add cmakeraw/cfsetspeed
 * [x] #566 - Add WaitStatus::PtraceSyscall for use with PTRACE_O_TRACESYSGOOD
 * [x] #610 - Failing mount tests
 * [x] #624 -  Enable ptrace on all Linux platforms
 * [x] #629 - Newtypes for uid_t, gid_t and pid_t
 * [x] #630 - Add wrappers for sysconf(3), pathconf(3), and fpathconf(3)
 * [x] #641 - Improve docs for `ioctl` module
 * [x] #659 - Potential double close in PtyMaster
 * [x] #681 - Remove feature flags
 * [x] #686 - Fix special ptraces

**Comment by Susurrus** [comment]
#610 doesn't affect things really, it's mostly a test/CI issue, so it doesn't matter if it's in a release so much as it gets fixed in git.

I'd actually suggest we wait until the next `libc` release for this as I'd like to get #527 merged we have a slew of other PRs that are pretty close. Specifically I'd like to nominate #566 and #629 which are pretty close and nice wins for `nix`. There are several others, but I don't think any are necessary fixes.

**Comment by asomers** [comment]
As long as we're committed to bumping libc anyway, then I'd like to finish PR #630 as well.

**Comment by Susurrus** [comment]
So the current list of PRs/issues I/we want addressed for 0.9 is:

 * [ ] #527 - Add cmakeraw/cfsetspeed
 * [ ] #566 - Add WaitStatus::PtraceSyscall for use with PTRACE_O_TRACESYSGOOD
 * [x] #610 - Failing mount tests
 * [ ] #624 -  Enable ptrace on all Linux platforms
 * [x] #629 - Newtypes for uid_t, gid_t and pid_t
 * [ ] #630 - Add wrappers for sysconf(3), pathconf(3), and fpathconf(3)
 * [ ] #641 - Improve docs for `ioctl` module

This doesn't include a general fix to `ptrace`, but I haven't dug into that yet and I hadn't filed an issue.

**Comment by Susurrus** [comment]
Well `libc` 0.2.25 was just released, so we're good with dependencies on that end. We should make sure we don't merge anything that has required changes to `libc` since 0.2.25.

**Comment by asomers** [comment]
I would like to add issue #659 to the list.  That kind of bug can take a long time to track down.

**Comment by Susurrus** [comment]
I'd also like to modify our release process for 0.9.0. The main thing is to reduce the number of steps by using `cargo-release`. This reduces several of the steps into 1, and basically we only need to modify the CHANGELOG and README for releases.

I don't know if we want to do it for this release, as I don't want to change the process too much in one go, but I'd also like us to use branches for our releases so it's easy to create patch releases. So only fix the `libc` version in a release branch and then migrate any desired PRs to that branch leaving any new ones to stay on `master`. This means that master is always "good" for merging new PRs since the libc version is still git.

**Comment by Susurrus** [comment]
We should also deal with #306 at some point, but exposing it to all the appropriate platforms will take another libc release. Maybe instead we limit it to the platforms that libc supports now, even if it's a reduction in platforms (which is better than the current status of it just not compiling).

**Comment by Susurrus** [comment]
#306 is fixed with #681, which was easy because the code was already broken so nobody has been using it for a while. We can add it back after the next libc release because rust-lang/libc#670 was already merged.

**Comment by Susurrus** [comment]
I just added #681 and #686 to the list as they both fix runtime and compilation bugs. I think we're stalled on #566 so I'd suggest we punt on it. The other 3 are getting close to merging.

**Comment by Susurrus** [comment]
@asomers in addition to #566 which is the only one we're blocking on now, there's two PRs addressing platform support. I hate to keep delaying this release, but I'd suggest we try to get #688 in as that's just to support compilation on that target (rustup really need to get support for OpenBSD!). And there's also #693 that would be good to improve our Android support.

My suggestion is to get them in and defer on all other PRs until #566 lands + 24 hours. Then we release. Thoughts?

**Comment by asomers** [comment]
I don't think it's worth holding up the release for #688.  Since we won't be building it in CI, it's likely to break again soon.  So OpenBSD users will probably have to pull in nix by specific known-good git revisions.  Basically, I think that releases aren't very relevant for Tier 3 and lower.  So I wouldn't hold up the release for it, though we can certainly merge it if it's ready in time.  I feel mostly the same way about #693, even though it's Tier 2.

**Comment by Susurrus** [comment]
@asomers Alright, I'm fine with that. We gotta cut a release at some point!

So with the release process, what were you thinking about for that? I'm going to be leaving in a few hours and out of town all weekend, but I'm fine with you releasing whenever you want here. As part of that I'd also like to suggest we also post an Announcement on https://users.rust-lang.org that gives a summary of the changes. I think that should probably be added to the release process notes if you agree.

**Comment by asomers** [comment]
Fixed by PR #705

**Comment by Susurrus** [comment]
Thanks, @asomers! And great job on the post to u.r-l.o. looks great and hopefully it'll recruit some new users and developers!
