### ISSUE TITLE
Migrate all FFI declarations to libc

### ISSUE THREAD

**Issue by Susurrus** [nix-rust/nix#748]
We should remove all FFI declarations within `nix` in favor of types defined in the `libc` crate. Much of this work has already been done recently, but there's still some left. And since we don't let any new PRs be merged until `libc` support has been added, we can resolve this problem relatively easily.

Left to address:
 * [ ] `src/sys/socket/mod.rs` (~~#746~~, #648)
 * [x] `src/sys/memfd.rs` (#794)
 * [x] `src/fcntl.rs` (see #745)
 * [x] `src/sched.rs` (see #747)
 * [x] `src/sys/quota.rs` (see #750)
 * [x] `src/sys/ptrace.rs` (see #749)
 * [x] `src/sys/syscall.rs` (see #747)
 * [x] `src/errno.rs` (see #798, #684, #807)

**Comment by Susurrus** [comment]
We're currently looking really good for this. The big stopper now is the rest of the FFI types for `socket`, otherwise I think we're all done.
